### ISSUE TITLE
在最近的思源版本中，浏览器编辑的白板无法同步到挂件中

### ISSUE THREAD

**Issue by EdmundDMa** [ooooooook/widget-excalidraw#16]
发现使用编辑功能绘图后，点击保存，然后刷新后，思源笔记中的挂件还是空白

**Comment by Cheng7966** [comment]
我的也是

**Comment by seeingrain** [comment]
我的也是，Siyuan升级到 3.1.4版本后，excalidraw 显示空白，编辑后再重新打开还是空白。

**Comment by emptylight370** [comment]
旧版本生成挂件块的自定义属性有一个data-assets，新版本思源更新之后创建的没有，所以没法显示白板。
临时解决方法是打开自定义属性添加`data-assets`属性，属性值就用未引用资源里找到的最新编辑的白板文件（要全部复制）。（启用自动保存之后会生成很多白板文件，注意分辨时间）
@EdmundDMa @Cheng7966 @seeingrain

**Comment by emptylight370** [comment]
```
Failed to load resource: net::ERR_CONNECTION_REFUSED      :50368/widgets/widget-excalidraw/dist//dist/excalidraw-assets/Virgil.woff2:1
Failed to load resource: the server responded with a status of 404 (Not Found)      Virgil.woff2:1
```
看起来这个是插件的报错，对应的文件跳转过去是插件的字体文件。
添加属性的代码没有发生报错，因为整个控制台没有打印其他报错。
而事实上发生的就是没能正确添加属性但是可以删除旧白板文件。如果添加属性报错，按照js运行类比应该会无法运行删除代码。
ps:字体实际上可以正确显示，就是慢一点。

**Comment by EdmundDMa** [comment]
我刚升级了思源最新的pre-release版本，似乎这个问题已经解决了，已经可以顺利编辑了。
https://github.com/siyuan-note/siyuan/releases/tag/v3.1.5-dev2
@lingfengyu-dreaming @Cheng7966 @seeingrain

**Comment by EdmundDMa** [comment]
升级最新版思源即可，似乎是思源的问题，哈哈
