### ISSUE TITLE
在思源笔记应用中直接点击编辑存在问题

### ISSUE THREAD

**Issue by zihaoliao** [ooooooook/widget-excalidraw#5]
### 问题
平台：windows；思源笔记版本：2.9.6；挂件版本：1.0.1
现象：在思源笔记中加入一个widget-excalidraw挂件，点击编辑，弹出来的浏览器页面为全空白。截图如下：
![image](https://github.com/ooooooook/widget-excalidraw/assets/7894966/afb738c9-274a-470d-9352-f9b60219475c)
必须要在浏览器中先打开思源笔记，然后在浏览中的思源笔记页面中点击编辑才能正常跳转到绘图页面，截图如下：
![image](https://github.com/ooooooook/widget-excalidraw/assets/7894966/a3b2d2e2-2d80-4078-a55c-2fc51336bcc1)
![image](https://github.com/ooooooook/widget-excalidraw/assets/7894966/21f551ae-f7cb-4228-925f-11046406564f)

**Comment by ooooooook** [comment]
@zihaoliao 你好，我刚测试了一下，可以正常打开。你重装挂件试试看行不行？

**Comment by tianyunperfect** [comment]
我也是同样的问题，2.9.6的版本，打开之后没有任何显示，昨天刚从2.9.4升级到2.9.6 不知道是不是这个原因。
挂件卸载重新安装都不行。

**Comment by tianyunperfect** [comment]
我知道了，是授权码的问题，没有授权码的时候，就会有权限问题。之前有授权码但是还是可以打开，现在不行了

**Comment by ooooooook** [comment]
@tianyunperfect 的确是授权问题，开启授权时思源伺服不会自动跳到授权页。修好了，等下思源集市更新。

**Comment by zihaoliao** [comment]
大佬们太牛了，插件更新至最新版本后，问题已解决。
