### ISSUE TITLE
请问如何设置画布边框，图画主体部分离边框太近了

### ISSUE THREAD

**Issue by rewalax** [ooooooook/widget-excalidraw#7]
请问如何设置画布边框，感觉图画主体部分离边框太近了

**Comment by ooooooook** [comment]
@rewalax 不是很明白你的意思，是指最后显示出来的图片内容太靠近边框了吗？目前excalidraw没有设置画布边框的API

**Comment by rewalax** [comment]
> @rewalax 不是很明白你的意思，是指最后显示出来的图片内容太靠近边框了吗？目前excalidraw没有设置画布边框的API

是的，就是您说的这个意思，在excalidraw官网试了下确实也无法设置边框距离，只能先这样了，感谢回复
